#!/usr/bin/env sh

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autoraise
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_shadow                off
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        0.93
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                on
yabai -m config active_window_border_topmost on
yabai -m config window_border_width          2
yabai -m config active_window_border_color   0xffBB000E
yabai -m config normal_window_border_color   0xff000000
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap
yabai -m rule --add app="Chromium" opacity=0.98
yabai -m rule --add app="^System Preferences" opacity=0.98
yabai -m rule --add app="mpv" opacity=0.98
yabai -m rule --add app="IINA" opacity=0.98
yabai -m rule --add app="Ferdi" opacity=0.98
yabai -m rule --add app="Microsoft Edge" opacity=0.98
yabai -m rule --add app="Brave" opacity=0.98
yabai -m rule --add app="Preview" opacity=0.98
yabai -m rule --add app="GIMP-2.10" opacity=0.98

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  06
yabai -m config bottom_padding               06
yabai -m config left_padding                 08
yabai -m config right_padding                08
yabai -m config window_gap                   06

yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="Authy Desktop" manage=off
yabai -m rule --add app="Genymotion*" manage=off
yabai -m rule --add app="Karabiner-Elements*" manage=off

yabai -m rule --add app="^Spotify$" space=6
echo "yabai configuration loaded.."
