oauth_token = "BhS_zbBzfWFF0KVj0yxkokaUoMS9LUsRKQmObYIF0AY.IaSAUH4LnIO3nACB7-RaJhwnUxLLysVwao_QdeACeb0"
expiration_time = "2024-01-17T23:58:39.822Z"
refresh_token = "6wKxw2toSws3y4qz4TUYiuo0KvE4TQHhO0o0-VB86HM.8LmYG9xuukPHKadG70VdimF1HaN32Zi32OEqIcq1NXo"
scopes = [
  "account:read",
  "user:read",
  "workers:write",
  "workers_kv:write",
  "workers_routes:write",
  "workers_scripts:write",
  "workers_tail:read",
  "d1:write",
  "pages:write",
  "zone:read",
  "ssl_certs:write",
  "constellation:write",
  "ai:read",
  "offline_access"
]
